
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shrey Pandey
 */
public class front extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public front() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        phon = new javax.swing.JTextField();
        unam = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        cpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(front.MAXIMIZED_BOTH);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("User Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 200, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 200, 40));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 200, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 200, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 200, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 200, 40));

        nam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 200, 40));

        phon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(phon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 200, 40));

        unam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(unam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, 200, 40));

        pass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 200, 40));

        cpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 200, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 200, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, 200, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("Sign In");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, 200, 40));

        back.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backround-03.jpg"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -370, 2690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if( !pass.getText().equals(cpass.getText()))JOptionPane.showMessageDialog(this, "Password don't Match");
else{
        try 
    {
Class.forName("java.sql.DriverManager");
Connection con = (Connection)   DriverManager.getConnection ("jdbc:mysql://localhost:3306/dbases", "root", "123");
Statement stmt = (Statement) con.createStatement(); 
String s1="select * from dbases where username='"+unam.getText()+"';"; 
ResultSet rs=stmt.executeQuery(s1);      if (rs.next())      {      JOptionPane.showMessageDialog(this, "Cant find UserName");}
else{String s="Insert into dbases values('"+nam.getText()+"','"+phon.getText()+"','"+unam.getText()+"','"+pass.getText()+"')"; 
    stmt.executeUpdate(s);
     String s2="create database '"+unam.getText()+"';";
    stmt.executeUpdate(s2);
    String s3="use '"+unam.getText()+"';";
    stmt.executeUpdate(s3);
    String s4="create table personal (First_Name varchar(30),Middle_Name varchar(30),Last_Name varchar(30),Company_Name varchar(100),Designation varchar(25),Website varchar(100),Birthday varchar(25),image varchar(100),phone varchar(15)) ;";
    stmt.executeUpdate(s4);
    String s5="create table phone (First_Name varchar(30),Middle_Name varchar(30),Last_Name varchar(30),Phone1 varchar(15),Phone2 varchar(15),Phone3 varchar(15),Phone4 varchar(15),Phone5 varchar(15),Phone6 varchar(15),Phone7 varchar(15),Phone8 varchar(15),Phone9 varchar(15),pty1 varchar(10),pty2 varchar(10),pty3 varchar(10),pty4 varchar(10),pty5 varchar(10),pty6 varchar(10),pty7 varchar(10),pty8 varchar(10),pty9 varchar(10) );";
    stmt.executeUpdate(s5);
    String s6="create table email (First_Name varchar(30),Middle_Name varchar(30),Last_Name varchar(30),email1 varchar(50),email2 varchar(50),email3 varchar(50),email4 varchar(50),email5 varchar(50),Phone varchar(15),ety1 varchar(10),ety2 varchar(10),ety3 varchar(10),ety4 varchar(10),ety5 varchar(10));";   
    stmt.executeUpdate(s6);
    String s7="create table address (First_Name varchar(30),Middle_Name varchar(30),Last_Name varchar(30),line1 varchar(50),line2 varchar(50),line3 varchar(50),country varchar(50),zip_code varchar(6),type varchar(10),phone varchar(15)) ;";
    stmt.executeUpdate(s7);
}}
catch(Exception e){}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nam;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phon;
    private javax.swing.JTextField unam;
    // End of variables declaration//GEN-END:variables
}
