
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shrey Pandey
 */
public class new_cont extends javax.swing.JFrame {

    /**
     * Creates new form new_cont
     */
    public new_cont() {
        initComponents();dateChooserSetter();
        
        //move();
    } 
    private void move(){
     new Timer(0, new ActionListener() {
 @Override
         public void actionPerformed(ActionEvent ae) {
            if(!"".equals(Phone1.getText())){Phone7.setVisible(true);phtype6.setVisible(true); phoney.setLocation(0,590);}
            else{Phone7.setVisible(false);phtype6.setVisible(false);phoney.setLocation(0, 540);}
            if(!"".equals(Phone7.getText())){Phone8.setVisible(true);phtype7.setVisible(true);phoney.setLocation(0, 640);}
            else{Phone8.setVisible(false);phtype7.setVisible(false);phoney.setLocation(0, 590);}
            if(!"".equals(Phone8.getText())){Phone2.setVisible(true);phtype1.setVisible(true);phoney.setLocation(0, 690);}
            else{Phone2.setVisible(false);phtype1.setVisible(false);phoney.setLocation(0, 640);}
            if(!"".equals(Phone2.getText())){Phone3.setVisible(true);phtype2.setVisible(true);phoney.setLocation(0, 740);}
            else{Phone3.setVisible(false);phtype2.setVisible(false);phoney.setLocation(0, 690);}
            if(!"".equals(Phone3.getText())){Phone4.setVisible(true);phtype3.setVisible(true);phoney.setLocation(0, 790);}
            else{Phone4.setVisible(false);phtype3.setVisible(false);phoney.setLocation(0, 740);}
            if(!"".equals(Phone4.getText())){Phone5.setVisible(true);phtype4.setVisible(true);phoney.setLocation(0, 840);}
            else{Phone5.setVisible(false);phtype4.setVisible(false);phoney.setLocation(0, 790);}
            if(!"".equals(Phone5.getText())){Phone6.setVisible(true);phtype5.setVisible(true);phoney.setLocation(0, 890);}
            else{Phone6.setVisible(false);phtype5.setVisible(false);phoney.setLocation(0, 840);}
            if(!"".equals(Phone6.getText())){Phone9.setVisible(true);phtype8.setVisible(true);phoney.setLocation(0, 940);}
            else{Phone9.setVisible(false);phtype8.setVisible(false);phoney.setLocation(0, 890);}
            if(!"someone@example.com".equals(Email4.getText())){Email5.setVisible(true);mailtype4.setVisible(true);emaily.setLocation(0, 110);}
            else{Email5.setVisible(false);mailtype4.setVisible(false);phoney.setLocation(0, 60);}
            if(!"someone@example.com".equals(Email5.getText())){Email1.setVisible(true);mailtype.setVisible(true);emaily.setLocation(0, 160);}
            else{Email1.setVisible(false);mailtype.setVisible(false);phoney.setLocation(0, 110);}
            if(!"someone@example.com".equals(Email1.getText())){Email2.setVisible(true);mailtype1.setVisible(true);emaily.setLocation(0, 210);}
            else{Email2.setVisible(false);phtype8.setVisible(false);phoney.setLocation(0, 160);}
            if(!"someone@example.com".equals(Email2.getText())){Email3.setVisible(true);mailtype2.setVisible(true);emaily.setLocation(0, 260);}
            else{Email3.setVisible(false);phtype8.setVisible(false);phoney.setLocation(0, 210);}
         }
     }).start();}
    static String s="/images.jpg",x="";
   
    private void dateChooserSetter() {
    int a,b,c;
    a=(Integer)date.getValue();b=(Integer)month.getValue();c=(Integer)year.getValue();
    if((c%4)==0){
    if(b==1||b==3||b==5||b==7||b==8||b==10||b==12){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));}
    else if(b==2){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 29, 1));}
    else{date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));}
    }
    else{if(b==1||b==3||b==5||b==7||b==8||b==10||b==12){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));}
    else if(b==2){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 28, 1));}
    else{date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));}
    }}
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        addb = new javax.swing.JButton();
        saveb = new javax.swing.JButton();
        cancelb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        Designation = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phtype = new javax.swing.JComboBox();
        companyName = new javax.swing.JTextField();
        Phone1 = new javax.swing.JFormattedTextField();
        phoney = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mailtype = new javax.swing.JComboBox();
        emaily = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addline1 = new javax.swing.JTextField();
        addline2 = new javax.swing.JTextField();
        addline3 = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        zipc = new javax.swing.JFormattedTextField();
        addtype = new javax.swing.JComboBox();
        adressy = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        website = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        year = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Email1 = new javax.swing.JTextField();
        mailtype1 = new javax.swing.JComboBox();
        Email2 = new javax.swing.JTextField();
        mailtype2 = new javax.swing.JComboBox();
        Email3 = new javax.swing.JTextField();
        mailtype3 = new javax.swing.JComboBox();
        Email4 = new javax.swing.JTextField();
        mailtype4 = new javax.swing.JComboBox();
        Email5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Phone2 = new javax.swing.JFormattedTextField();
        phtype1 = new javax.swing.JComboBox();
        Phone3 = new javax.swing.JFormattedTextField();
        phtype2 = new javax.swing.JComboBox();
        Phone4 = new javax.swing.JFormattedTextField();
        phtype3 = new javax.swing.JComboBox();
        Phone5 = new javax.swing.JFormattedTextField();
        phtype4 = new javax.swing.JComboBox();
        Phone6 = new javax.swing.JFormattedTextField();
        phtype5 = new javax.swing.JComboBox();
        Phone7 = new javax.swing.JFormattedTextField();
        phtype6 = new javax.swing.JComboBox();
        Phone8 = new javax.swing.JFormattedTextField();
        phtype7 = new javax.swing.JComboBox();
        Phone9 = new javax.swing.JFormattedTextField();
        phtype8 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(new_cont.MAXIMIZED_BOTH);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 460, 300));

        addb.setBackground(new java.awt.Color(0, 0, 255));
        addb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addb.setForeground(new java.awt.Color(255, 255, 255));
        addb.setText("Add / Replace Image");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });
        jPanel1.add(addb, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 200, 40));

        saveb.setBackground(new java.awt.Color(0, 0, 255));
        saveb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveb.setForeground(new java.awt.Color(255, 255, 255));
        saveb.setText("Save Contact");
        saveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebActionPerformed(evt);
            }
        });
        jPanel1.add(saveb, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 225, 40));

        cancelb.setBackground(new java.awt.Color(0, 0, 255));
        cancelb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelb.setForeground(new java.awt.Color(255, 255, 255));
        cancelb.setText("Cancel\n");
        cancelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbActionPerformed(evt);
            }
        });
        jPanel1.add(cancelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 225, 40));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Company");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 220, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 220, 40));

        lastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastName.setForeground(new java.awt.Color(153, 153, 153));
        lastName.setText("Last Name");
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 220, 40));

        middleName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        middleName.setForeground(new java.awt.Color(153, 153, 153));
        middleName.setText("Middle Name");
        middleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middleNameFocusLost(evt);
            }
        });
        jPanel1.add(middleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 220, 40));

        Designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Designation.setForeground(new java.awt.Color(153, 153, 153));
        Designation.setText("Designation");
        Designation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DesignationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DesignationFocusLost(evt);
            }
        });
        jPanel1.add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 220, 40));

        firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstname.setForeground(new java.awt.Color(153, 153, 153));
        firstname.setText("First Name");
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 220, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Phone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 220, 40));

        phtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Pager", "Other" }));
        jPanel1.add(phtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 140, 40));

        companyName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        companyName.setForeground(new java.awt.Color(153, 153, 153));
        companyName.setText("Company Name");
        companyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFocusLost(evt);
            }
        });
        jPanel1.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 700, 40));

        Phone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone1CaretUpdate(evt);
            }
        });
        Phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone1ActionPerformed(evt);
            }
        });
        Phone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone1KeyPressed(evt);
            }
        });
        jPanel1.add(Phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 220, 40));

        phoney.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Email");
        phoney.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 40));

        mailtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        phoney.add(mailtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, 140, 40));

        emaily.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Address");
        emaily.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 40));

        addline1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addline1.setForeground(new java.awt.Color(153, 153, 153));
        addline1.setText("Address Line 1");
        addline1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline1FocusLost(evt);
            }
        });
        emaily.add(addline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 700, 40));

        addline2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addline2.setForeground(new java.awt.Color(153, 153, 153));
        addline2.setText("Address Line 2");
        addline2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline2FocusLost(evt);
            }
        });
        emaily.add(addline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 700, 40));

        addline3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addline3.setForeground(new java.awt.Color(153, 153, 153));
        addline3.setText("Address Line 3");
        addline3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline3FocusLost(evt);
            }
        });
        emaily.add(addline3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 700, 40));

        country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        country.setForeground(new java.awt.Color(153, 153, 153));
        country.setText("Country");
        country.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                countryCaretUpdate(evt);
            }
        });
        country.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFocusLost(evt);
            }
        });
        emaily.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 370, 40));

        zipc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        zipc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emaily.add(zipc, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 170, 160, 40));

        addtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home", "Work" }));
        emaily.add(addtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 140, 40));

        adressy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Website");
        adressy.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("Birthday");
        adressy.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 220, 40));

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adressy.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 160, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Date");
        adressy.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 50, 40));

        website.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adressy.add(website, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 470, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Month");
        adressy.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 50, 40));

        month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        month.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthMousePressed(evt);
            }
        });
        month.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                monthStateChanged(evt);
            }
        });
        month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthFocusGained(evt);
            }
        });
        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthKeyPressed(evt);
            }
        });
        adressy.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 160, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Year");
        adressy.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 50, 40));

        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2017, 1));
        year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearMouseClicked(evt);
            }
        });
        year.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yearStateChanged(evt);
            }
        });
        adressy.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 160, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrey Pandey\\Downloads\\backround-03.jpg")); // NOI18N
        adressy.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 150));

        emaily.add(adressy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1360, 180));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrey Pandey\\Downloads\\backround-03.jpg")); // NOI18N
        emaily.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 360));

        phoney.add(emaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1360, 370));

        Email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email1.setForeground(new java.awt.Color(153, 153, 153));
        Email1.setText("someone@example.com");
        Email1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email1CaretUpdate(evt);
            }
        });
        Email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email1FocusLost(evt);
            }
        });
        phoney.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 470, 40));

        mailtype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        phoney.add(mailtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 140, 40));

        Email2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email2.setForeground(new java.awt.Color(153, 153, 153));
        Email2.setText("someone@example.com");
        Email2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email2CaretUpdate(evt);
            }
        });
        Email2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email2FocusLost(evt);
            }
        });
        phoney.add(Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 470, 40));

        mailtype2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        phoney.add(mailtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 140, 40));

        Email3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email3.setForeground(new java.awt.Color(153, 153, 153));
        Email3.setText("someone@example.com");
        Email3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email3CaretUpdate(evt);
            }
        });
        Email3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email3FocusLost(evt);
            }
        });
        phoney.add(Email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 470, 40));

        mailtype3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        phoney.add(mailtype3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 140, 40));

        Email4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email4.setForeground(new java.awt.Color(153, 153, 153));
        Email4.setText("someone@example.com");
        Email4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email4CaretUpdate(evt);
            }
        });
        Email4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email4FocusLost(evt);
            }
        });
        phoney.add(Email4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 470, 40));

        mailtype4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        phoney.add(mailtype4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 140, 40));

        Email5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email5.setForeground(new java.awt.Color(153, 153, 153));
        Email5.setText("someone@example.com");
        Email5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email5CaretUpdate(evt);
            }
        });
        Email5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email5FocusLost(evt);
            }
        });
        phoney.add(Email5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 470, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrey Pandey\\Downloads\\backround-03.jpg")); // NOI18N
        phoney.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 260));

        jPanel1.add(phoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 940, 1360, 620));

        Phone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone2CaretUpdate(evt);
            }
        });
        Phone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone2KeyPressed(evt);
            }
        });
        jPanel1.add(Phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 220, 40));

        phtype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, 140, 40));

        Phone3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone3CaretUpdate(evt);
            }
        });
        Phone3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone3KeyPressed(evt);
            }
        });
        jPanel1.add(Phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 220, 40));

        phtype2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 140, 40));

        Phone4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone4CaretUpdate(evt);
            }
        });
        Phone4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone4KeyPressed(evt);
            }
        });
        jPanel1.add(Phone4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 750, 220, 40));

        phtype3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 750, 140, 40));

        Phone5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone5CaretUpdate(evt);
            }
        });
        Phone5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone5KeyPressed(evt);
            }
        });
        jPanel1.add(Phone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 800, 220, 40));

        phtype4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 800, 140, 40));

        Phone6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone6CaretUpdate(evt);
            }
        });
        Phone6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone6KeyPressed(evt);
            }
        });
        jPanel1.add(Phone6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 850, 220, 40));

        phtype5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 850, 140, 40));

        Phone7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone7CaretUpdate(evt);
            }
        });
        Phone7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone7KeyPressed(evt);
            }
        });
        jPanel1.add(Phone7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 220, 40));

        phtype6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 140, 40));

        Phone8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone8CaretUpdate(evt);
            }
        });
        Phone8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone8KeyPressed(evt);
            }
        });
        jPanel1.add(Phone8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 220, 40));

        phtype7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 140, 40));

        Phone9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone9.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone9CaretUpdate(evt);
            }
        });
        Phone9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone9KeyPressed(evt);
            }
        });
        jPanel1.add(Phone9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 900, 220, 40));

        phtype8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        jPanel1.add(phtype8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 900, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shrey Pandey\\Downloads\\backround-03.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1370, 1570));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
 
  int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser1.getSelectedFile();
        try {s= file.getAbsolutePath();
        int a,n=1;String temp,temp1=s;
        a=s.length();
        while(a>0){
            temp=temp1.toString().substring(0,1);
            temp1=temp1.toString().substring( 1);
            if("\\".equals(temp))
            {temp="/";}
            x=x+temp;a--;
        }
        System.out.print(x);
         image.setIcon(new javax.swing.ImageIcon(s)); 
        } catch (Exception ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    
    }//GEN-LAST:event_addbActionPerformed

    private void cancelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbActionPerformed

    private void monthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMouseClicked
    }//GEN-LAST:event_monthMouseClicked

    private void yearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearMouseClicked
    }//GEN-LAST:event_yearMouseClicked

    private void monthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMousePressed
    }//GEN-LAST:event_monthMousePressed

    private void monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFocusGained
    }//GEN-LAST:event_monthFocusGained

    private void monthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyPressed
    }//GEN-LAST:event_monthKeyPressed

    private void monthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_monthStateChanged
dateChooserSetter();        // TODO add your handling code here:
    }//GEN-LAST:event_monthStateChanged

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
if ("First Name".equals(firstname.getText()))
{   firstname.setForeground(new java.awt.Color(0,0,0));
  firstname.setText(""); }     
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
if ("".equals(firstname.getText())){firstname.setForeground(new java.awt.Color(153,153,153));
    firstname.setText("First Name");}
    }//GEN-LAST:event_firstnameFocusLost

    private void middleNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameFocusGained
 if ("Middle Name".equals(middleName.getText()))
{   middleName.setForeground(new java.awt.Color(0,0,0));
    middleName.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFocusGained

    private void middleNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameFocusLost
if ("".equals(middleName.getText())){middleName.setForeground(new java.awt.Color(153,153,153));
    middleName.setText("Middle Name");}        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFocusLost

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
if ("".equals(lastName.getText())){lastName.setForeground(new java.awt.Color(153,153,153));
    lastName.setText("First Name");}        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFocusLost

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
 if ("Last Name".equals(lastName.getText()))
{   lastName.setForeground(new java.awt.Color(0,0,0));
    lastName.setText(""); }             // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFocusGained

    private void companyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusGained
if ("Company Name".equals(companyName.getText()))
{   companyName.setForeground(new java.awt.Color(0,0,0));
    companyName.setText(""); }              // TODO add your handling code here:
    }//GEN-LAST:event_companyNameFocusGained

    private void companyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusLost
       if ("".equals(companyName.getText())){companyName.setForeground(new java.awt.Color(153,153,153));
    companyName.setText("Company Name");}  
    }//GEN-LAST:event_companyNameFocusLost

    private void DesignationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DesignationFocusGained
  if ("Designation".equals(Designation.getText()))
{   Designation.setForeground(new java.awt.Color(0,0,0));
    Designation.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationFocusGained

    private void DesignationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DesignationFocusLost
     if ("".equals(Designation.getText())){Designation.setForeground(new java.awt.Color(153,153,153));
    Designation.setText("Designation");}  
    }//GEN-LAST:event_DesignationFocusLost

    private void addline1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1FocusGained
      if ("Address Line 1".equals(addline1.getText()))
{   addline1.setForeground(new java.awt.Color(0,0,0));
    addline1.setText(""); }   
    }//GEN-LAST:event_addline1FocusGained

    private void addline1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1FocusLost
        if ("".equals(addline1.getText())){addline1.setForeground(new java.awt.Color(153,153,153));
    addline1.setText("Address Line 1");}  
    }//GEN-LAST:event_addline1FocusLost

    private void addline2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline2FocusGained
    if ("Address Line 2".equals(addline2.getText()))
{   addline2.setForeground(new java.awt.Color(0,0,0));
    addline2.setText(""); }   
    }//GEN-LAST:event_addline2FocusGained

    private void addline2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline2FocusLost
       if ("".equals(addline2.getText())){addline2.setForeground(new java.awt.Color(153,153,153));
    addline2.setText("Address Line 2");}  
    }//GEN-LAST:event_addline2FocusLost

    private void addline3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline3FocusGained
        if ("Address Line 3".equals(addline3.getText()))
{   addline3.setForeground(new java.awt.Color(0,0,0));
    addline3.setText(""); } 
    }//GEN-LAST:event_addline3FocusGained

    private void addline3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline3FocusLost
     if ("".equals(addline3.getText())){addline3.setForeground(new java.awt.Color(153,153,153));
    addline3.setText("Address Line 3");}  
    }//GEN-LAST:event_addline3FocusLost

    private void countryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusGained
  if ("Country".equals(country.getText()))
{   country.setForeground(new java.awt.Color(0,0,0));
    country.setText(""); } 
    }//GEN-LAST:event_countryFocusGained

    private void countryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusLost
      if ("".equals(country.getText())){country.setForeground(new java.awt.Color(153,153,153));
    country.setText("Country");} 
    }//GEN-LAST:event_countryFocusLost

    private void yearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yearStateChanged
dateChooserSetter();        // TODO add your handling code here:
    }//GEN-LAST:event_yearStateChanged

    private void Email1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email1FocusGained
     if ("someone@example.com".equals(Email1.getText()))
{   addline3.setForeground(new java.awt.Color(0,0,0));
    addline3.setText(""); }    // TODO add your handling code here:
    }//GEN-LAST:event_Email1FocusGained

    private void Email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email1FocusLost
    if ("".equals(Email1.getText())){Email1.setForeground(new java.awt.Color(153,153,153));
    Email1.setText("someone@example.com");}      // TODO add your handling code here:
    }//GEN-LAST:event_Email1FocusLost

    private void Phone1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone1CaretUpdate
//int a=phoney.getY(),i=1;
  //      if("".equals(Phone1.getText())){phoney.setLocation(0, 540);}
//else{  phoney.setLocation(0, 600);
  //      }  
    }//GEN-LAST:event_Phone1CaretUpdate

    private void Phone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone1KeyPressed
 
    }//GEN-LAST:event_Phone1KeyPressed

    private void Email1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email1CaretUpdate
//int a=emaily.getY();
  //      if("someone@example.com".equals(Email1.getText())||"".equals(Email1.getText())){emaily.setLocation(0, 60);}
//else{  emaily.setLocation(0, 60+60);}
    }//GEN-LAST:event_Email1CaretUpdate

    private void countryCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_countryCaretUpdate
  
    }//GEN-LAST:event_countryCaretUpdate

    private void savebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebActionPerformed

String a=month.getValue().toString(),b=date.getValue().toString();
String firstn,middlen,lastn,company,designation,phone1,addressl1,addressl2,addressl3,coun,zic,addtyp,websit,dob,email2,email3,email4,email5,email,phone2,phone3,phone4,phone5,phone6,phone7,phone8,phone9;
String ptype1,ptype2,ptype3,ptype4,ptype5,ptype6,ptype7,ptype8,ptype9,etype1,etype2,etype3,etype4,etype5;
firstn=firstname.getText();middlen=middleName.getText();lastn=lastName.getText();
phone3=Phone8.getText();ptype3=phtype7.getSelectedItem().toString();
phone5=Phone3.getText();ptype5=phtype2.getSelectedItem().toString();
phone6=Phone4.getText();ptype6=phtype3.getSelectedItem().toString();
phone7=Phone5.getText();ptype7=phtype4.getSelectedItem().toString();
phone1=Phone1.getText();ptype1=phtype.getSelectedItem().toString();
phone4=Phone2.getText();ptype4=phtype1.getSelectedItem().toString();
phone8=Phone6.getText();ptype8=phtype5.getSelectedItem().toString();
phone9=Phone9.getText();ptype9=phtype8.getSelectedItem().toString();
phone2=Phone7.getText();ptype2=phtype6.getSelectedItem().toString();
email2=Email5.getText();etype2=mailtype3.getSelectedItem().toString();
email3=Email1.getText();etype3=mailtype4.getSelectedItem().toString();
email4=Email2.getText();etype4=mailtype.getSelectedItem().toString();
email5=Email3.getText();etype5=mailtype1.getSelectedItem().toString();
email=Email4.getText();etype1=mailtype2.getSelectedItem().toString();
company=companyName.getText();designation=Designation.getText();
addressl1=addline1.getText();addressl2=addline2.getText();addressl3=addline3.getText();coun=country.getText();addtyp=(addtype.getSelectedItem()).toString();zic=zipc.getText();
if ("First Name".equals(firstn)){firstn="";}
if ("Middle Name".equals(middlen)){middlen="";}
if ("Last Name".equals(lastn)){lastn="";}
if ("Company Name".equals(company)){company="";}
if ("Designation".equals(designation)){designation="";}
if ("someone@example.com".equals(email2)){email2="";}
if ("someone@example.com".equals(email3)){email3="";}
if ("someone@example.com".equals(email4)){email4="";}
if ("someone@example.com".equals(email5)){email5="";}
if ("someone@example.com".equals(email)){email="";}
if ("Address Line 1".equals(addressl1)){addressl1="";}
if ("Address Line 2".equals(addressl2)){addressl2="";}
if ("Address Line 3".equals(addressl3)){addressl3="";}
if ("Country".equals(coun)){coun="";}
if(a.length()==1){a="0"+a;}
if(b.length()==1){b="0"+b;}
dob=(b+"/"+a+"/"+year.getValue());websit=website.getText();
try{    Class.forName("java.sql.DriverManager");   
Connection con = (Connection)   DriverManager.getConnection ("jdbc:mysql://localhost:3306/address_book","root","123");
Statement stmt = (Statement) con.createStatement(); 
if("".equals(x)){x="/images.jpg";}
String query1="INSERT INTO personal VALUES  ('"+firstn+"','"+middlen+"','"+lastn+"','"+company+"','"+designation+"','"+websit+"','"+dob+"','"+x+"','"+phone1+"');";
String query2="INSERT INTO phone VALUES ('"+firstn+"','"+middlen+"','"+lastn+"','"+phone1+"','"+phone2+"','"+phone3+"','"+phone4+"','"+phone5+"','"+phone6+"','"+phone7+"','"+phone8+"','"+phone9+"','"+ptype1+"','"+ptype2+"','"+ptype3+"','"+ptype4+"','"+ptype5+"','"+ptype6+"','"+ptype7+"','"+ptype8+"','"+ptype9+"');";
String query3="INSERT INTO email VALUES ('"+firstn+"','"+middlen+"','"+lastn+"','"+email+"','"+email2+"','"+email3+"','"+email4+"','"+email5+"','"+phone1+"','"+etype1+"','"+etype2+"','"+etype3+"','"+etype4+"','"+etype5+"');";
String query4="INSERT INTO address VALUES  ('"+firstn+"','"+middlen+"','"+lastn+"','"+addressl1+"','"+addressl2+"','"+addressl3+"','"+coun+"','"+zic+"','"+addtyp+"','"+phone1+"');";
stmt.executeUpdate(query1);stmt.executeUpdate(query2);stmt.executeUpdate(query3); stmt.executeUpdate(query4);
this.setVisible(false);}
catch(Exception e)  {   JOptionPane.showMessageDialog (this, e.getMessage());  }

    }//GEN-LAST:event_savebActionPerformed

    private void Phone2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone2CaretUpdate

    private void Phone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone2KeyPressed

    private void Phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone1ActionPerformed

    private void Phone3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone3CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone3CaretUpdate

    private void Phone3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone3KeyPressed

    private void Phone4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone4CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone4CaretUpdate

    private void Phone4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone4KeyPressed

    private void Phone5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone5CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone5CaretUpdate

    private void Phone5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone5KeyPressed

    private void Phone6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone6CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone6CaretUpdate

    private void Phone6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone6KeyPressed

    private void Phone7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone7CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone7CaretUpdate

    private void Phone7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone7KeyPressed

    private void Phone8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone8CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone8CaretUpdate

    private void Phone8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone8KeyPressed

    private void Phone9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone9CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone9CaretUpdate

    private void Phone9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone9KeyPressed

    private void Email2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email2CaretUpdate

    private void Email2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email2FocusGained
    if ("someone@example.com".equals(Email2.getText()))
{   Email2.setForeground(new java.awt.Color(0,0,0));
    Email2.setText(""); }      // TODO add your handling code here:
    }//GEN-LAST:event_Email2FocusGained

    private void Email2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email2FocusLost

    private void Email3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email3CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email3CaretUpdate

    private void Email3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email3FocusGained
     if ("someone@example.com".equals(Email3.getText()))
{   Email3.setForeground(new java.awt.Color(0,0,0));
    Email3.setText(""); }     // TODO add your handling code here:
    }//GEN-LAST:event_Email3FocusGained

    private void Email3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email3FocusLost

    private void Email4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email4CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email4CaretUpdate

    private void Email4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email4FocusGained
  if ("someone@example.com".equals(Email4.getText()))
{   Email4.setForeground(new java.awt.Color(0,0,0));
    Email4.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_Email4FocusGained

    private void Email4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email4FocusLost

    private void Email5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email5CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email5CaretUpdate

    private void Email5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email5FocusGained
  if ("someone@example.com".equals(Email5.getText()))
{   Email5.setForeground(new java.awt.Color(0,0,0));
    Email5.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_Email5FocusGained

    private void Email5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email5FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_cont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_cont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_cont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_cont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_cont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Designation;
    private javax.swing.JTextField Email1;
    private javax.swing.JTextField Email2;
    private javax.swing.JTextField Email3;
    private javax.swing.JTextField Email4;
    private javax.swing.JTextField Email5;
    private javax.swing.JFormattedTextField Phone1;
    private javax.swing.JFormattedTextField Phone2;
    private javax.swing.JFormattedTextField Phone3;
    private javax.swing.JFormattedTextField Phone4;
    private javax.swing.JFormattedTextField Phone5;
    private javax.swing.JFormattedTextField Phone6;
    private javax.swing.JFormattedTextField Phone7;
    private javax.swing.JFormattedTextField Phone8;
    private javax.swing.JFormattedTextField Phone9;
    private javax.swing.JButton addb;
    private javax.swing.JTextField addline1;
    private javax.swing.JTextField addline2;
    private javax.swing.JTextField addline3;
    private javax.swing.JComboBox addtype;
    private javax.swing.JPanel adressy;
    private javax.swing.JButton cancelb;
    private javax.swing.JTextField companyName;
    private javax.swing.JTextField country;
    private javax.swing.JSpinner date;
    private javax.swing.JPanel emaily;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel image;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JComboBox mailtype;
    private javax.swing.JComboBox mailtype1;
    private javax.swing.JComboBox mailtype2;
    private javax.swing.JComboBox mailtype3;
    private javax.swing.JComboBox mailtype4;
    private javax.swing.JTextField middleName;
    private javax.swing.JSpinner month;
    private javax.swing.JPanel phoney;
    private javax.swing.JComboBox phtype;
    private javax.swing.JComboBox phtype1;
    private javax.swing.JComboBox phtype2;
    private javax.swing.JComboBox phtype3;
    private javax.swing.JComboBox phtype4;
    private javax.swing.JComboBox phtype5;
    private javax.swing.JComboBox phtype6;
    private javax.swing.JComboBox phtype7;
    private javax.swing.JComboBox phtype8;
    private javax.swing.JButton saveb;
    private javax.swing.JTextField website;
    private javax.swing.JSpinner year;
    private javax.swing.JFormattedTextField zipc;
    // End of variables declaration//GEN-END:variables
}
