
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shrey Pandey
 */
public class view_edit extends javax.swing.JFrame {

    /**
     * Creates new form view_edit
     */
    public view_edit() {
        initComponents();dateChooserSetter();
        saveb.setVisible(false);
        addb.setVisible(false);
 
}
    public void stat(){try 
    {String m ;
Class.forName("java.sql.DriverManager");
Connection con = (Connection)   DriverManager.getConnection ("jdbc:mysql://localhost:3306/address_book", "root", "123");
Statement stmt = (Statement) con.createStatement();  
String query="SELECT * FROM personal WHERE phone='"+pyx.b+"';";  
ResultSet rs=stmt.executeQuery(query);    
while(rs.next()) {
String first_name = rs.getString("First_Name"); firstname.setText(first_name);
String middle_name  = rs.getString("Middle_Name");middleName.setText(middle_name);
String last_name = rs.getString("Last_Name");      lastName.setText(last_name);
String Company_name = rs.getString("Company_Name");     companyName.setText(Company_name);
String Designation1 = rs.getString("Designation");     Designation.setText(Designation1);
String Website = rs.getString("Website");      website.setText(Website);Phone1.setText(pyx.b);
String bday= rs.getString("Birthday"),a,b,c; bday=bday.trim();a=bday.substring(0,2);b=bday.substring(3,5);c=bday.substring(6,10);
date.setValue(Integer.parseInt(a));month.setValue(Integer.parseInt(b));year.setValue(Integer.parseInt(c));
String Image = rs.getString("image");      if(Image==null){}
else {
    image.setIcon(new javax.swing.ImageIcon(Image));
}
}
String query4="SELECT * FROM phone WHERE Phone1='"+pyx.b+"';";  
ResultSet rs4=stmt.executeQuery(query4);
while(rs4.next()) {
String phone2 = rs4.getString("Phone2");Phone7.setText(phone2);
String phone3 = rs4.getString("Phone3");Phone8.setText(phone3);
String phone4 = rs4.getString("Phone4");Phone2.setText(phone4);
String phone5 = rs4.getString("Phone5");Phone3.setText(phone5);
String phone6 = rs4.getString("Phone6");Phone4.setText(phone6);
String phone7 = rs4.getString("Phone7");Phone5.setText(phone7);
String phone8 = rs4.getString("Phone8");Phone6.setText(phone8);
String phone9 = rs4.getString("Phone9");Phone9.setText(phone9);
}
String query1="SELECT * FROM email WHERE phone='"+pyx.b+"';";  
ResultSet rs1=stmt.executeQuery(query1);
while(rs1.next()) {
String email = rs1.getString("email1");email1.setText(email);
String email2 = rs1.getString("email2");Email5.setText(email2);
String email3= rs1.getString("email3");Email1.setText(email3);
String email4 = rs1.getString("email4");Email2.setText(email4);
String email5 = rs1.getString("email5");Email3.setText(email5);
}
String query2="SELECT * FROM address WHERE phone='"+pyx.b+"';";  
ResultSet rs2=stmt.executeQuery(query2);
while(rs2.next()) {
String line1 = rs2.getString("line1");addline1.setText(line1);
String line2 = rs2.getString("line2");addline2.setText(line2);
String line3 = rs2.getString("line3");addline3.setText(line3);
String Country = rs2.getString("country");country.setText(Country);
String zipc1 = rs2.getString("zip_code");zipc.setText(zipc1);

 }}
catch(Exception e) 
{ 
    JOptionPane.showMessageDialog(this, e.getMessage()); }
        String m;
  }
    static String s;
private void dateChooserSetter() {
    int a,b,c;
    a=(Integer)date.getValue();b=(Integer)month.getValue();c=(Integer)year.getValue();
    if((c%4)==0){
   if(b==1||b==3||b==5||b==7||b==8||b==10||b==12){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));}
    else if(b==2){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 29, 1));}
    else{date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));}
    }
    else{if(b==1||b==3||b==5||b==7||b==8||b==10||b==12){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));}
    else if(b==2){
    date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 28, 1));}
    else{date.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));}
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        addb = new javax.swing.JButton();
        editb = new javax.swing.JButton();
        saveb = new javax.swing.JButton();
        cancelb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        Designation = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phtype = new javax.swing.JComboBox();
        companyName = new javax.swing.JTextField();
        Phone1 = new javax.swing.JFormattedTextField();
        phoney = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mailtype = new javax.swing.JComboBox();
        email1 = new javax.swing.JTextField();
        emaily = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addline1 = new javax.swing.JTextField();
        addline2 = new javax.swing.JTextField();
        addline3 = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        zipc = new javax.swing.JFormattedTextField();
        addtype = new javax.swing.JComboBox();
        adressy = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        website = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        year = new javax.swing.JSpinner();
        Email5 = new javax.swing.JTextField();
        mailtype4 = new javax.swing.JComboBox();
        Email1 = new javax.swing.JTextField();
        mailtype1 = new javax.swing.JComboBox();
        Email2 = new javax.swing.JTextField();
        mailtype2 = new javax.swing.JComboBox();
        Email3 = new javax.swing.JTextField();
        mailtype3 = new javax.swing.JComboBox();
        Phone7 = new javax.swing.JFormattedTextField();
        phtype6 = new javax.swing.JComboBox();
        Phone8 = new javax.swing.JFormattedTextField();
        phtype7 = new javax.swing.JComboBox();
        Phone2 = new javax.swing.JFormattedTextField();
        phtype1 = new javax.swing.JComboBox();
        phtype2 = new javax.swing.JComboBox();
        Phone3 = new javax.swing.JFormattedTextField();
        Phone4 = new javax.swing.JFormattedTextField();
        Phone5 = new javax.swing.JFormattedTextField();
        Phone6 = new javax.swing.JFormattedTextField();
        Phone9 = new javax.swing.JFormattedTextField();
        phtype3 = new javax.swing.JComboBox();
        phtype4 = new javax.swing.JComboBox();
        phtype5 = new javax.swing.JComboBox();
        phtype8 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(view_edit.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 455, 300));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        jPanel2.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 460, 300));

        addb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addb.setText("Add / Replace Image");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });
        jPanel2.add(addb, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 200, 40));

        editb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editb.setText("Edit Contact");
        editb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbActionPerformed(evt);
            }
        });
        jPanel2.add(editb, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 220, 40));

        saveb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveb.setText("Save Contact");
        saveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebActionPerformed(evt);
            }
        });
        jPanel2.add(saveb, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 225, 40));

        cancelb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelb.setText("Cancel\n");
        cancelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbActionPerformed(evt);
            }
        });
        jPanel2.add(cancelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 225, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Company");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 220, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 220, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 220, 40));

        lastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastName.setForeground(new java.awt.Color(153, 153, 153));
        lastName.setText("Last Name");
        lastName.setEnabled(false);
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        jPanel2.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 220, 40));

        middleName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        middleName.setForeground(new java.awt.Color(153, 153, 153));
        middleName.setText("Middle Name");
        middleName.setEnabled(false);
        middleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middleNameFocusLost(evt);
            }
        });
        jPanel2.add(middleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 220, 40));

        Designation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Designation.setForeground(new java.awt.Color(153, 153, 153));
        Designation.setText("Designation");
        Designation.setEnabled(false);
        Designation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DesignationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DesignationFocusLost(evt);
            }
        });
        jPanel2.add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 220, 40));

        firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstname.setForeground(new java.awt.Color(153, 153, 153));
        firstname.setText("First Name");
        firstname.setEnabled(false);
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 220, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Phone");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 220, 40));

        phtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype.setEnabled(false);
        jPanel2.add(phtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 140, 40));

        companyName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        companyName.setForeground(new java.awt.Color(153, 153, 153));
        companyName.setText("Company Name");
        companyName.setEnabled(false);
        companyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFocusLost(evt);
            }
        });
        jPanel2.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 700, 40));

        Phone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone1.setEnabled(false);
        Phone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone1CaretUpdate(evt);
            }
        });
        Phone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone1KeyPressed(evt);
            }
        });
        jPanel2.add(Phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 220, 40));

        phoney.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Email");
        phoney.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 40));

        mailtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        mailtype.setEnabled(false);
        phoney.add(mailtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 140, 40));

        email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(153, 153, 153));
        email1.setText("someone@example.com");
        email1.setEnabled(false);
        email1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                email1CaretUpdate(evt);
            }
        });
        email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email1FocusLost(evt);
            }
        });
        phoney.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 470, 40));

        emaily.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Address");
        emaily.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 40));

        addline1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addline1.setForeground(new java.awt.Color(153, 153, 153));
        addline1.setText("Address Line 1");
        addline1.setEnabled(false);
        addline1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline1FocusLost(evt);
            }
        });
        emaily.add(addline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 700, 40));

        addline2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addline2.setForeground(new java.awt.Color(153, 153, 153));
        addline2.setText("Address Line 2");
        addline2.setEnabled(false);
        addline2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline2FocusLost(evt);
            }
        });
        emaily.add(addline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 700, 40));

        addline3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addline3.setForeground(new java.awt.Color(153, 153, 153));
        addline3.setText("Address Line 3");
        addline3.setEnabled(false);
        addline3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addline3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addline3FocusLost(evt);
            }
        });
        emaily.add(addline3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 700, 40));

        country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        country.setForeground(new java.awt.Color(153, 153, 153));
        country.setText("Country");
        country.setEnabled(false);
        country.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                countryCaretUpdate(evt);
            }
        });
        country.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFocusLost(evt);
            }
        });
        emaily.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 370, 40));

        zipc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        zipc.setEnabled(false);
        zipc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emaily.add(zipc, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 170, 160, 40));

        addtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home", "Work" }));
        addtype.setEnabled(false);
        emaily.add(addtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 140, 40));

        adressy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Website");
        adressy.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Birthday");
        adressy.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 220, 40));

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setEnabled(false);
        adressy.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 160, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Date");
        adressy.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 50, 40));

        website.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        website.setEnabled(false);
        adressy.add(website, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 470, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Month");
        adressy.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 50, 40));

        month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        month.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        month.setEnabled(false);
        month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthMousePressed(evt);
            }
        });
        month.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                monthStateChanged(evt);
            }
        });
        month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthFocusGained(evt);
            }
        });
        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthKeyPressed(evt);
            }
        });
        adressy.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 160, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Year");
        adressy.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 50, 40));

        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2017, 1));
        year.setEnabled(false);
        year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearMouseClicked(evt);
            }
        });
        year.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yearStateChanged(evt);
            }
        });
        adressy.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 160, 40));

        emaily.add(adressy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1360, 160));

        phoney.add(emaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1360, 360));

        Email5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email5.setForeground(new java.awt.Color(153, 153, 153));
        Email5.setText("someone@example.com");
        Email5.setEnabled(false);
        Email5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email5CaretUpdate(evt);
            }
        });
        Email5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email5FocusLost(evt);
            }
        });
        phoney.add(Email5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 470, 40));

        mailtype4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        mailtype4.setEnabled(false);
        phoney.add(mailtype4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 140, 40));

        Email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email1.setForeground(new java.awt.Color(153, 153, 153));
        Email1.setText("someone@example.com");
        Email1.setEnabled(false);
        Email1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email1CaretUpdate(evt);
            }
        });
        Email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email1FocusLost(evt);
            }
        });
        phoney.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 470, 40));

        mailtype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        mailtype1.setEnabled(false);
        phoney.add(mailtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, 140, 40));

        Email2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email2.setForeground(new java.awt.Color(153, 153, 153));
        Email2.setText("someone@example.com");
        Email2.setEnabled(false);
        Email2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email2CaretUpdate(evt);
            }
        });
        Email2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email2FocusLost(evt);
            }
        });
        phoney.add(Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 470, 40));

        mailtype2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        mailtype2.setEnabled(false);
        phoney.add(mailtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 140, 40));

        Email3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email3.setForeground(new java.awt.Color(153, 153, 153));
        Email3.setText("someone@example.com");
        Email3.setEnabled(false);
        Email3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Email3CaretUpdate(evt);
            }
        });
        Email3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email3FocusLost(evt);
            }
        });
        phoney.add(Email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 470, 40));

        mailtype3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailtype3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Home", "Other" }));
        mailtype3.setEnabled(false);
        phoney.add(mailtype3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 140, 40));

        jPanel2.add(phoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 940, 1360, 620));

        Phone7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone7.setEnabled(false);
        Phone7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone7CaretUpdate(evt);
            }
        });
        Phone7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone7KeyPressed(evt);
            }
        });
        jPanel2.add(Phone7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 220, 40));

        phtype6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype6.setEnabled(false);
        jPanel2.add(phtype6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 140, 40));

        Phone8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone8.setEnabled(false);
        Phone8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone8CaretUpdate(evt);
            }
        });
        Phone8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone8KeyPressed(evt);
            }
        });
        jPanel2.add(Phone8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 220, 40));

        phtype7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype7.setEnabled(false);
        jPanel2.add(phtype7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 140, 40));

        Phone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone2.setEnabled(false);
        Phone2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone2CaretUpdate(evt);
            }
        });
        Phone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone2KeyPressed(evt);
            }
        });
        jPanel2.add(Phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 220, 40));

        phtype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype1.setEnabled(false);
        jPanel2.add(phtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, 140, 40));

        phtype2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype2.setEnabled(false);
        jPanel2.add(phtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 140, 40));

        Phone3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone3.setEnabled(false);
        Phone3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone3CaretUpdate(evt);
            }
        });
        Phone3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone3KeyPressed(evt);
            }
        });
        jPanel2.add(Phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 220, 40));

        Phone4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone4.setEnabled(false);
        Phone4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone4CaretUpdate(evt);
            }
        });
        Phone4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone4KeyPressed(evt);
            }
        });
        jPanel2.add(Phone4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 750, 220, 40));

        Phone5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone5.setEnabled(false);
        Phone5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone5CaretUpdate(evt);
            }
        });
        Phone5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone5KeyPressed(evt);
            }
        });
        jPanel2.add(Phone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 800, 220, 40));

        Phone6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone6.setEnabled(false);
        Phone6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone6CaretUpdate(evt);
            }
        });
        Phone6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone6KeyPressed(evt);
            }
        });
        jPanel2.add(Phone6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 850, 220, 40));

        Phone9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Phone9.setEnabled(false);
        Phone9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phone9.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Phone9CaretUpdate(evt);
            }
        });
        Phone9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Phone9KeyPressed(evt);
            }
        });
        jPanel2.add(Phone9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 900, 220, 40));

        phtype3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype3.setEnabled(false);
        jPanel2.add(phtype3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 750, 140, 40));

        phtype4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype4.setEnabled(false);
        jPanel2.add(phtype4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 800, 140, 40));

        phtype5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype5.setEnabled(false);
        jPanel2.add(phtype5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 850, 140, 40));

        phtype8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phtype8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobile", "Work", "Home", "Main", "Pager", "Other" }));
        phtype8.setEnabled(false);
        jPanel2.add(phtype8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 900, 140, 40));

        jPanel1.add(jPanel2);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed

        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
                s= file.getAbsolutePath();
                image.setIcon(new javax.swing.ImageIcon(s));
            } catch (Exception ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_addbActionPerformed

    private void savebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebActionPerformed
        String a=month.getValue().toString(),b=date.getValue().toString();
        String firstn,middlen,lastn,company,designation,phone1,addressl1,addressl2,addressl3,coun,zic,addtyp,websit,dob,email=email1.getText(),phone2=null,phone3=null,phone4=null,phone5=null,phone6=null,phone7=null,phone8=null,phone9=null;
        firstn=firstname.getText();middlen=middleName.getText();lastn=lastName.getText();String email2=null,email3=null,email4=null,email5=null;
        company=companyName.getText();designation=Designation.getText();phone1=Phone1.getText();
        addressl1=addline1.getText();addressl2=addline2.getText();addressl3=addline3.getText();coun=country.getText();addtyp=(addtype.getSelectedItem()).toString();zic=zipc.getText();
        if(a.length()==1){a="0"+a;}
        if(b.length()==1){b="0"+b;}
        dob=(b+"/"+a+"/"+year.getValue());websit=website.getText();
        try{    Class.forName("java.sql.DriverManager");
            Connection con = (Connection)   DriverManager.getConnection ("jdbc:mysql://localhost:3306/address_book","root","123");
            Statement stmt = (Statement) con.createStatement();
            String query1="Update personal set First_name='"+firstn+"',Middle_Name='"+middlen+"',Last_Name='"+lastn+"',Company_Name='"+company+"',Designation='"+designation+"',Website='"+websit+"',Birthday='"+dob+"',image='"+s+"',phone='"+phone1+"' where phone='"+pyx.b+"';";
            String query2="Update phone set First_name='"+firstn+"',Middle_Name='"+middlen+"',Last_Name='"+lastn+"',Phone1='"+phone1+"',Phone2='"+phone2+"',Phone3='"+phone3+"',Phone4='"+phone4+"',Phone5='"+phone5+"',Phone6='"+phone6+"',Phone7='"+phone7+"',Phone8='"+phone8+"',Phone9='"+phone9+"' where Phone1='"+pyx.b+"';";
            String query3="Update email set First_name='"+firstn+"',Middle_Name='"+middlen+"',Last_Name='"+lastn+"',email1='"+email+"',email2='"+email2+"',email3='"+email3+"',email4='"+email4+"',email5='"+email5+"',phone='"+phone1+"' where phone='"+pyx.b+"';";
            String query4="Update address set First_name='"+firstn+"',Middle_Name='"+middlen+"',Last_Name='"+lastn+"',line1='"+addressl1+"',line2='"+addressl2+"',line3='"+addressl3+"',country='"+coun+"',zip_code='"+zic+"',type='"+addtyp+"',phone='"+phone1+"' where phone='"+pyx.b+"';";
            stmt.executeUpdate(query1);stmt.executeUpdate(query2);stmt.executeUpdate(query3); stmt.executeUpdate(query4);
            this.setVisible(false);}
        catch(Exception e)  {   JOptionPane.showMessageDialog (this, e.getMessage());  }
    }//GEN-LAST:event_savebActionPerformed

    private void cancelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbActionPerformed

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
        if ("Last Name".equals(lastName.getText()))
        {   lastName.setForeground(new java.awt.Color(0,0,0));
            lastName.setText(""); }             // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFocusGained

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        if ("".equals(lastName.getText())){lastName.setForeground(new java.awt.Color(153,153,153));
            lastName.setText("First Name");}        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFocusLost

    private void middleNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameFocusGained
        if ("Middle Name".equals(middleName.getText()))
        {   middleName.setForeground(new java.awt.Color(0,0,0));
            middleName.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFocusGained

    private void middleNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameFocusLost
        if ("".equals(middleName.getText())){middleName.setForeground(new java.awt.Color(153,153,153));
            middleName.setText("Middle Name");}        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFocusLost

    private void DesignationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DesignationFocusGained
        if ("Designation".equals(Designation.getText()))
        {   Designation.setForeground(new java.awt.Color(0,0,0));
            Designation.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationFocusGained

    private void DesignationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DesignationFocusLost
        if ("".equals(Designation.getText())){Designation.setForeground(new java.awt.Color(153,153,153));
            Designation.setText("Designation");}
    }//GEN-LAST:event_DesignationFocusLost

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        if ("First Name".equals(firstname.getText()))
        {   firstname.setForeground(new java.awt.Color(0,0,0));
            firstname.setText(""); }
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        if ("".equals(firstname.getText())){firstname.setForeground(new java.awt.Color(153,153,153));
            firstname.setText("First Name");}
    }//GEN-LAST:event_firstnameFocusLost

    private void companyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusGained
        if ("Company Name".equals(companyName.getText()))
        {   companyName.setForeground(new java.awt.Color(0,0,0));
            companyName.setText(""); }              // TODO add your handling code here:
    }//GEN-LAST:event_companyNameFocusGained

    private void companyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusLost
        if ("".equals(companyName.getText())){companyName.setForeground(new java.awt.Color(153,153,153));
            companyName.setText("Company Name");}
    }//GEN-LAST:event_companyNameFocusLost

    private void Phone1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone1CaretUpdate
        int a=phoney.getY(),i=1;
        if("".equals(Phone1.getText())){phoney.setLocation(0, 540);}
        else{  phoney.setLocation(0, 600);
        }

    }//GEN-LAST:event_Phone1CaretUpdate

    private void Phone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone1KeyPressed

    }//GEN-LAST:event_Phone1KeyPressed

    private void email1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_email1CaretUpdate
        int a=emaily.getY();
        if("someone@example.com".equals(email1.getText())||"".equals(email1.getText())){emaily.setLocation(0, 60);}
        else{  emaily.setLocation(0, 60+60);}
    }//GEN-LAST:event_email1CaretUpdate

    private void email1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email1FocusGained
        if ("someone@example.com".equals(email1.getText()))
        {   email1.setForeground(new java.awt.Color(0,0,0));
            email1.setText(""); }       // TODO add your handling code here:
    }//GEN-LAST:event_email1FocusGained

    private void email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email1FocusLost
        if ("".equals(email1.getText())){email1.setForeground(new java.awt.Color(153,153,153));
            email1.setText("someone@example.com");}      // TODO add your handling code here:
    }//GEN-LAST:event_email1FocusLost

    private void addline1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1FocusGained
        if ("Address Line 1".equals(addline1.getText()))
        {   addline1.setForeground(new java.awt.Color(0,0,0));
            addline1.setText(""); }
    }//GEN-LAST:event_addline1FocusGained

    private void addline1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline1FocusLost
        if ("".equals(addline1.getText())){addline1.setForeground(new java.awt.Color(153,153,153));
            addline1.setText("Address Line 1");}
    }//GEN-LAST:event_addline1FocusLost

    private void addline2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline2FocusGained
        if ("Address Line 2".equals(addline2.getText()))
        {   addline2.setForeground(new java.awt.Color(0,0,0));
            addline2.setText(""); }
    }//GEN-LAST:event_addline2FocusGained

    private void addline2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline2FocusLost
        if ("".equals(addline2.getText())){addline2.setForeground(new java.awt.Color(153,153,153));
            addline2.setText("Address Line 2");}
    }//GEN-LAST:event_addline2FocusLost

    private void addline3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline3FocusGained
        if ("Address Line 3".equals(addline3.getText()))
        {   addline3.setForeground(new java.awt.Color(0,0,0));
            addline3.setText(""); }
    }//GEN-LAST:event_addline3FocusGained

    private void addline3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addline3FocusLost
        if ("".equals(addline3.getText())){addline3.setForeground(new java.awt.Color(153,153,153));
            addline3.setText("Address Line 3");}
    }//GEN-LAST:event_addline3FocusLost

    private void countryCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_countryCaretUpdate

    }//GEN-LAST:event_countryCaretUpdate

    private void countryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusGained
        if ("Country".equals(country.getText()))
        {   country.setForeground(new java.awt.Color(0,0,0));
            country.setText(""); }
    }//GEN-LAST:event_countryFocusGained

    private void countryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusLost
        if ("".equals(country.getText())){country.setForeground(new java.awt.Color(153,153,153));
            country.setText("Country");}
    }//GEN-LAST:event_countryFocusLost

    private void monthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMouseClicked

    }//GEN-LAST:event_monthMouseClicked

    private void monthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMousePressed

    }//GEN-LAST:event_monthMousePressed

    private void monthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_monthStateChanged
        dateChooserSetter();        // TODO add your handling code here:
    }//GEN-LAST:event_monthStateChanged

    private void monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFocusGained

    }//GEN-LAST:event_monthFocusGained

    private void monthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyPressed

    }//GEN-LAST:event_monthKeyPressed

    private void yearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearMouseClicked

    }//GEN-LAST:event_yearMouseClicked

    private void yearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yearStateChanged
        dateChooserSetter();        // TODO add your handling code here:
    }//GEN-LAST:event_yearStateChanged

    private void editbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbActionPerformed
     addb.setVisible(true);
     Designation.setEnabled(true);
     Phone1.setEnabled(true);
     addline1.setEnabled(true);
     addline2.setEnabled(true);
     addline3.setEnabled(true);
     addtype.setEnabled(true);
     companyName.setEnabled(true);
     country.setEnabled(true);
     date.setEnabled(true);
     email1.setEnabled(true);
     firstname.setEnabled(true);
     lastName.setEnabled(true);
     mailtype.setEnabled(true);
     middleName.setEnabled(true);
     month.setEnabled(true);
     website.setEnabled(true);
     year.setEnabled(true);
     zipc.setEnabled(true);
     editb.setVisible(false);
     saveb.setVisible(true);
     phtype.setEnabled(true);
     Phone7.setEnabled(true);phtype6.setEnabled(true);
     Phone8.setEnabled(true);phtype7.setEnabled(true);
     Phone2.setEnabled(true);phtype1.setEnabled(true);
     Phone3.setEnabled(true);phtype2.setEnabled(true);
     Phone4.setEnabled(true);phtype3.setEnabled(true);
     Phone5.setEnabled(true);phtype4.setEnabled(true);
     Phone6.setEnabled(true);phtype5.setEnabled(true);
     Phone9.setEnabled(true);phtype8.setEnabled(true);
     Email5.setEnabled(true);mailtype4.setEnabled(true);
     Email1.setEnabled(true);mailtype1.setEnabled(true);
     Email2.setEnabled(true);mailtype2.setEnabled(true);
     Email3.setEnabled(true);mailtype3.setEnabled(true);
    }//GEN-LAST:event_editbActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     stat();   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Phone7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone7CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone7CaretUpdate

    private void Phone7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone7KeyPressed

    private void Phone8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone8CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone8CaretUpdate

    private void Phone8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone8KeyPressed

    private void Phone2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone2CaretUpdate

    private void Phone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone2KeyPressed

    private void Phone3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone3CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone3CaretUpdate

    private void Phone3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone3KeyPressed

    private void Phone4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone4CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone4CaretUpdate

    private void Phone4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone4KeyPressed

    private void Phone5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone5CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone5CaretUpdate

    private void Phone5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone5KeyPressed

    private void Phone6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone6CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone6CaretUpdate

    private void Phone6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone6KeyPressed

    private void Phone9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Phone9CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone9CaretUpdate

    private void Phone9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone9KeyPressed

    private void Email5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email5CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email5CaretUpdate

    private void Email5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email5FocusGained
        if ("someone@example.com".equals(Email5.getText()))
        {   Email5.setForeground(new java.awt.Color(0,0,0));
            Email5.setText(""); }        // TODO add your handling code here:
    }//GEN-LAST:event_Email5FocusGained

    private void Email5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email5FocusLost

    private void Email1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email1CaretUpdate
        //int a=emaily.getY();
        //      if("someone@example.com".equals(Email1.getText())||"".equals(Email1.getText())){emaily.setLocation(0, 60);}
        //else{  emaily.setLocation(0, 60+60);}
    }//GEN-LAST:event_Email1CaretUpdate

    private void Email1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email1FocusGained
        if ("someone@example.com".equals(Email1.getText()))
        {   addline3.setForeground(new java.awt.Color(0,0,0));
            addline3.setText(""); }    // TODO add your handling code here:
    }//GEN-LAST:event_Email1FocusGained

    private void Email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email1FocusLost
        if ("".equals(Email1.getText())){Email1.setForeground(new java.awt.Color(153,153,153));
            Email1.setText("someone@example.com");}      // TODO add your handling code here:
    }//GEN-LAST:event_Email1FocusLost

    private void Email2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email2CaretUpdate

    private void Email2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email2FocusGained
        if ("someone@example.com".equals(Email2.getText()))
        {   Email2.setForeground(new java.awt.Color(0,0,0));
            Email2.setText(""); }      // TODO add your handling code here:
    }//GEN-LAST:event_Email2FocusGained

    private void Email2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email2FocusLost

    private void Email3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Email3CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Email3CaretUpdate

    private void Email3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email3FocusGained
        if ("someone@example.com".equals(Email3.getText()))
        {   Email3.setForeground(new java.awt.Color(0,0,0));
            Email3.setText(""); }     // TODO add your handling code here:
    }//GEN-LAST:event_Email3FocusGained

    private void Email3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Email3FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Designation;
    private javax.swing.JTextField Email1;
    private javax.swing.JTextField Email2;
    private javax.swing.JTextField Email3;
    private javax.swing.JTextField Email5;
    private javax.swing.JFormattedTextField Phone1;
    private javax.swing.JFormattedTextField Phone2;
    private javax.swing.JFormattedTextField Phone3;
    private javax.swing.JFormattedTextField Phone4;
    private javax.swing.JFormattedTextField Phone5;
    private javax.swing.JFormattedTextField Phone6;
    private javax.swing.JFormattedTextField Phone7;
    private javax.swing.JFormattedTextField Phone8;
    private javax.swing.JFormattedTextField Phone9;
    private javax.swing.JButton addb;
    private javax.swing.JTextField addline1;
    private javax.swing.JTextField addline2;
    private javax.swing.JTextField addline3;
    private javax.swing.JComboBox addtype;
    private javax.swing.JPanel adressy;
    private javax.swing.JButton cancelb;
    private javax.swing.JTextField companyName;
    private javax.swing.JTextField country;
    private javax.swing.JSpinner date;
    private javax.swing.JButton editb;
    private javax.swing.JTextField email1;
    private javax.swing.JPanel emaily;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel image;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JComboBox mailtype;
    private javax.swing.JComboBox mailtype1;
    private javax.swing.JComboBox mailtype2;
    private javax.swing.JComboBox mailtype3;
    private javax.swing.JComboBox mailtype4;
    private javax.swing.JTextField middleName;
    private javax.swing.JSpinner month;
    private javax.swing.JPanel phoney;
    private javax.swing.JComboBox phtype;
    private javax.swing.JComboBox phtype1;
    private javax.swing.JComboBox phtype2;
    private javax.swing.JComboBox phtype3;
    private javax.swing.JComboBox phtype4;
    private javax.swing.JComboBox phtype5;
    private javax.swing.JComboBox phtype6;
    private javax.swing.JComboBox phtype7;
    private javax.swing.JComboBox phtype8;
    private javax.swing.JButton saveb;
    private javax.swing.JTextField website;
    private javax.swing.JSpinner year;
    private javax.swing.JFormattedTextField zipc;
    // End of variables declaration//GEN-END:variables
}
